### ISSUE TITLE
Remove "receiving" addresses from request outputs.

### ISSUE THREAD

**Issue by KarlTheProgrammer** [tokenized/specification#45]
Change transfer and related receiving addresses to not be in the outputs of the request action, only in the data.

**Comment by KarlTheProgrammer** [comment]
Dang It! I put #44 in the commit. Here is the [commit](https://github.com/tokenized/specification/commit/5e009827ae25e61c3ccd90905525a8ac9f5e8f7b).

**Comment by daftspunk** [comment]
Rationale: This reduces two deposits of dust, being used to identify and send tokens to an address, down to one deposit. It also makes it so the the receivers are unaware of a transfer until it has been settled

**Comment by daftspunk** [comment]
The docs should be updated to reflect this change also. Paste the link to the commit for review

**Comment by KarlTheProgrammer** [comment]
I didn't find any required updates to the website for this change.

**Comment by daftspunk** [comment]
Added a minor note to the docs in https://github.com/tokenized/docs/commit/6122a2bd5d7bc6f54bce87e19cdb7edff1de8264

Thanks!
