### ISSUE TITLE
SupportingDocs field type enhancement

### ISSUE THREAD

**Issue by daftspunk** [tokenized/specification#51]
The following actions have a `SupportingDocs` field
- C1 Contract Offer
- C2 Contract Formation
- C4 Static Contract Formation

This field should be enhanced to support multiple files.

Replace
- SupportingDocsFileType
- SupportingDocs

With just SupportingDocs as type `Document[]`, then this type can contain the 
- file MIME type
- file name (including extension)
- file hash/file contents
- compression type (0 - none, 1 - 7zip, etc)

**Comment by daftspunk** [comment]
Looking good. The [Static Contract Formation](https://github.com/tokenized/specification/blob/master/src/protocol/develop/actions/C4%20-%20Static%20Contract%20Formation.yaml) is still on the old definition:

- `SupportingDocsFileType`
- `SupportingDocs`

Once this is fixed should be good to go

**Comment by KarlTheProgrammer** [comment]
Sorry about that. It should be good now.

**Comment by daftspunk** [comment]
Looks good! Thanks
