### ISSUE TITLE
Voting Permitted/Rejected for Frozen Assets

### ISSUE THREAD

**Issue by eamesyi** [tokenized/specification#81]
AKB raised a good point that there will likely be many use cases where users of frozen tokens should be able to continue to partake in corporate actions (voting).  I think the innocent while proven guilty philosophy is important here and companies still need to operate during lengthy legal proceedings.

Long term, I believe we need to add a flag to either permit or reject voting for frozen assets.  However, I think this may be overly-complicated for where we are in the development cycle and I think it is preferable to simply allow voting with frozen actions for now.

@KarlTheProgrammer thoughts?

**Comment by KarlTheProgrammer** [comment]
I can think of three options for this. 

#### Most Complex Option
1. Add flag to asset definition that enables voting with shares of that asset when frozen.
2. Add permission flag that allows votes using that asset to include frozen shares.
3. Add flag to proposal to enable voting with frozen shares.

These options can be combined. For example, 1 could set the default behavior for the asset, 2 can specify differences between fields (i.e. some field amendments can't be voted on by frozen shares), and 3 controls per vote. This might be more complex than what we want though.

#### Standard Option
Allow freeze action to specify if the holder still retains voting rights. This leaves it up to the enforcement authority.

#### Simplest Option
Just treat all frozen shares the same as unfrozen shares for voting purposes. This might not be "friendly" to governments that don't follow the "innocent until proven guilty" policy, which is many if not most.

If frozen shares are not eligible to vote, then we need to determine if they count towards the total shares when applying absolute voting system rules.

**Comment by daftspunk** [comment]
This should be defined by the voting system

**Comment by eamesyi** [comment]
I think we should just treat all frozen shares the same as unfrozen shares for voting purposes for now.  I want to minimize complexity until we get MVP done.  There will be plenty of time to refine this later down the track.
